### PR TITLE
Aruba OS Unicon Plugin

### PR DESCRIPTION
**Pull request by Alexpf20210007**
This Aruba Unicon Plugin will login to an Aruba device. I have tested with and without proxy. I have tested multiple devices. I have also tested a script that has Cisco IOS and Aruba AOS devices at one time. This script is a work in progress but I would like to contribute what I have accomplished so far to the project. I have only tested a show command at this time and but I  believe that this will configure Aruba devices now. I have added the test plugin and it ran 14 tests on my machine and passed with Ok. 
I have also used it to run scripts in production. I have ran the scripts on over 100 devices and received output using genie parsers that I have also scripted. There are a lot of things that I can take out of the scripts that are not necessary as well. Thank you so much for this opportunity and I look forward to publishing Genie parsers for Unicon for which I already have a show vlan command parser working for aos.

### CODE REVIEW

**Comment by Alexpf20210007** [comment]
Can I get somebody to review this pull request?

**Comment by stevedhn** [comment]
> Can I get somebody to review this pull request?

Hi I assigned @omehrabi , who's also the maintainer of unicon plugins, for the new plugins like this, we need more time to review

**Comment by Alexpf20210007** [comment]
Is there a time frame that this will be reviewed?

**Review by GerriorL — CHANGES_REQUESTED** [review]
Hi Alex,
This looks good to me, however I need to ask you to create a changelog to note what was added. You can find the template in docs/changelog_plugins/undistributed which is the same location where the changelog should be saved. It also needs to have an ISO date at the end of the changelog name, before the .rst

**Comment by omehrabi** [comment]
Hi,
I checked  the service implementation and I dont see any any changes. I think we already support aos so if there is no new functionality it should work fine with the current settings

**Comment by Alexpf20210007** [comment]
Hello,

The new functionality is that when connecting to many AOS devices, you have to press any key to continue during the login. Also, aos is not a supported plugin. I added that similar to how dnos6 and 10 were added previously.

Thank you,

Alex Pfeil, NETWORK LEAD ENGINEER
AMERICAN FAMILY INSURANCE
6000 American Parkway | B3149 / Q15P | Madison, WI 53783
Office: 844-927-2446 ext. 47538  | Mobile: 937.602.9546

**Comment by Alexpf20210007** [comment]
@omehrabi - If you look at the Unicon Plugins support files, you will see that I added aos.
@GerriorL - I added the file that you requested.

**Review by GerriorL — APPROVED** [review]

**Review by stevedhn — APPROVED** [review]

**Comment by Alexpf20210007** [comment]
Thank you so much for getting this reviewed. Is there anything else I need to do to get added into the next update?

**Comment by Alexpf20210007** [comment]
Is this still going to be added this month?

**Comment by stevedhn** [comment]
> Is this still going to be added this month?

you haven't merged the pull request, in order for it to appear in the next release, you have to merge the PR.

**Comment by Alexpf20210007** [comment]
I don't have write access to merge the pull request.

**Comment by stevedhn** [comment]
> I don't have write access to merge the pull request.

I add @GerriorL here, who's in charge of the deployment

**Comment by GerriorL** [comment]
pyATS 22.8 is releasing tomorrow. Once that process is complete this will be merged.

**Comment by Alexpf20210007** [comment]
I synced the branch to the master so it should be good to go @GerriorL.

**Comment by GerriorL** [comment]
Thanks!

**Comment by GerriorL** [comment]
Hi Alex,

When attempting to integrate this into 22.9 it has caused breakages in internal components. More investigation is needed so we need to pull this for the time being.

As a note, unicon does its own logging, so please remove all logging from your PR. It might be good to reference how other platforms handle what you are trying to do, and approaching it in the same way.

**Pull request merged**
