### PR TITLE
added github actions

### PR DESCRIPTION
**Pull request by tahigash**
adding GitHub actions to check UTs.

latest github actions result : https://github.com/CiscoTestAutomation/unicon.plugins/runs/3264319182

### CODE REVIEW

**Review by GerriorL — APPROVED** [review]

**Comment by danielgraziano** [comment]
I think this needs to be talked about internally more. 

1. these unittests shouldnt be taking this long to run
2. each 'group' iteration sets up its own env

**Review by danielgraziano — CHANGES_REQUESTED** [review]
I think this needs to be talked about internally more.

1. these unittests shouldnt be taking this long to run
2. each 'group' iteration sets up its own env

**Review by danielgraziano — APPROVED** [review]
merge for now since blocking. but we need to improve this

**Comment by tahigash** [comment]
> I think this needs to be talked about internally more.
> 
> 1. these unittests shouldnt be taking this long to run
> 2. each 'group' iteration sets up its own env

we can discuss. but shouldn't be blocker to add checks since now not testing UTs on public github even when merging contributed PRs.

**Pull request merged**
